### ISSUE TITLE
repo init fails

### ISSUE THREAD

**Issue by erpri** [octavosystems/osd32mp1-debian#1]
`repo init -u https://github.com/octavosystems/osd32mp1-debian` failed by responsing `fatal: Couldn't find remote ref refs/heads/master` 

It looks like the branch is not "master" but "main". 

Adding `repo init -u https://github.com/octavosystems/osd32mp1-debian -b main` solves the issue.

**Comment by neerajdantu** [comment]
Thank you! Updated README to communicate this fix.
