### ISSUE TITLE
Updated Linux to 5.10.x, u-boot to 2020.10

### ISSUE THREAD

**Issue by jcwren** [octavosystems/osd32mp1-debian#3]
Are there any plans to update the kernel to something recent (such as 5.10.x), along with u-boot?

Robert C. Nelson and ST have support for the STM32MP1 using these versions, and it would be nice to have a correctly working SPI driver.

**Comment by neerajdantu** [comment]
Updated to be compatible with OpenSTLinux v3.0 with 5.10 kernel
